# using-handlers.yml
---
- host: webservers
  gather_facts: yes
  become: true

  vars:
    httpd_log_level: error
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: latest

    - name: Update configuration
      template:
        src: /home/ansible/httpd.conf.js
        dest: /etc/httpd/conf/httpd.conf
      notify: httpd service

  handlers:
    - name: httpd service
      service:
        name: httpd
        start: restarted
      listen: httpd service
