# loop-2.yml
---
- host: webservers
  gather_facts: yes
  become: true

  vars_files:
    - vars.yml

  tasks:
    - name: Check and start services
      service:
        name: "{{ item }}"
        start: started

      loop: "{{ service_list }}"
