#  delete-ami.yml
---
- hosts: localhost
  gather_facts: no

  vars:
    - ansible_python_interpreter: /usr/bin/python3

  var_files:
    - keys.yml

  tasks:
    - name: Create a new ec2 AMI
      amazon.aws.ec2_ami:
        aws_access_key: "{{AWS_ACCESS_KEY_ID}}"
        aws_secret_key: "{{AWS_SECRET_ACCESS_KEY}}"
        ec2_region: "{{AWS_REGION}}"
        image_id: ami-074b59301a1716e90
        name: my-new-ami
        wait: yes
        state: absent
