#  gather-facts.yml
---
- hosts: localhost
  gather_facts: yes

  vars:
    - ansible_python_interpreter: /usr/bin/python3
  var_files:
    - keys.yml
  tasks:
    - name: Get instances facts
      amazon.aws.ec2_instance_info:
        aws_access_key: "{{AWS_ACCESS_KEY_ID}}"
        aws_secret_key: "{{AWS_SECRET_ACCESS_KEY}}"
        ec2_region: "{{AWS_REGION}}"
        filters:
          # use either of the followings
          instance-state-name:["running"] # could be an array: ["running","stopped","pending" etc]
          # or
          # availability-zone: us-west-1
          # or
          # "tag:Name":"Demo"
      register: ec2_facts
    - debug:
        var: ec2_facts
