---
- hosts: localhost
  gather_facts: no
  vars:
    - ansible_python_interpreter: /usr/bin/python3
  var_files:
    - keys.yml

  tasks:
    - name: Get AMI facts
      amazon.aws.ec2_ami_info:
        aws_access_key: "{{AWS_ACCESS_KEY_ID}}"
        aws_secret_key: "{{AWS_SECRET_ACCESS_KEY}}"
        ec2_region: "{{AWS_REGION}}"
        owner: "{{AWS_OWNER}}"
      register: ami_facts

    - name: Output the facts info
      debug:
        msg: "{{item.name}}"
      loop_control:
        label: "{{item.image_id}}"
      loop: "{{ami_facts.images}}"
