#  #  ec2-metadata.yml
---
- hosts: localhost
  gather_facts: yes

  vars:
    - ansible_python_interpreter: /usr/bin/python3
  var_files:
    - keys.yml
  tasks:
    - name: Get instances info by tag
      amazon.aws.ec2_instance_info:
        aws_access_key: "{{AWS_ACCESS_KEY_ID}}"
        aws_secret_key: "{{AWS_SECRET_ACCESS_KEY}}"
        ec2_region: "{{AWS_REGION}}"
        instance_ids: i-024b030df5d46c6d1
        state: running
        wait: yes
        tags:
          Name: Ansible-Demo
      register: ec2 

    - name: Output IP address of instances 
      debug:
        msg: "{{item_public_ip_address}}"
      loop: "{{ec2.instances}}"
      
    - name: Add host to inventory
      add_host:
        hostname: "{{item_public_ip_address}}"
        groupname: demogroup
        ansible_ssh_common_args: "o- StrictHostKeyChecking=no"
        ansible_ssh_provate_key_file: ~/.ssh/ansiblekey.pem
      loop: "{{ec2.instances}}"

- hosts: demogroup
  gather_facts: no
  remote-user: ec2-user

  task: 
    - name: Wait for ssh connection
      wait_for_connection:
        delay: 5
        timeout: 90

    - name: Collect instance facts
      amazon.aws.ec2_metadata_facts:
      register: ec2

- hosts: localhost
  gather_facts: yes

  vars_files:
    - keys.yml

  task: 
    - name: Checkout gathered facts
    debug:
      var: hostvars[group['demogroup'][0]['ansible_ec2_instance_id']]

    - name: Change instances state by tag
      amazon.aws.ec2_instance:
        aws_access_key: "{{AWS_ACCESS_KEY_ID}}"
        aws_secret_key: "{{AWS_SECRET_ACCESS_KEY}}"
        ec2_region: "{{AWS_REGION}}"
        instance_ids: i-024b030df5d46c6d1
        state: stopped
        tags:
          Name: Ansible-Demo
      register: ec2


       
       
